export const PLANS = {
  free: {
    name: 'Free',
    price: 0,
    priceLabel: '$0',
    period: null,
    captionHoursPerMonth: null,
    aiFallbackHoursPerMonth: null,
    allowanceLabel: 'Unlimited web transcripts',
    apiAccess: false,
    dashboard: false,
    webhooks: false,
    channelSync: false,
    batch: false,
    maxWebhooks: 0,
    maxChannels: 0,
    maxBatchUrls: 0,
    cta: 'Start for free',
    ctaHref: '/',
    featured: false,
    description: 'For individuals who need quick transcripts.',
    features: [
      'Unlimited web transcripts',
      'AI summary',
      'Download JSON, SRT, TXT, VTT',
      'Search and highlight',
      'No sign-up required',
    ],
    missing: ['No API access', 'No automation'],
  },
  api: {
    name: 'Developer',
    price: 9,
    priceLabel: '$9',
    period: '/ month',
    captionHoursPerMonth: 1000,
    aiFallbackHoursPerMonth: 50,
    allowanceLabel: '1,000 caption hours + 50 AI fallback hours',
    apiAccess: true,
    dashboard: true,
    webhooks: true,
    channelSync: false,
    batch: false,
    maxWebhooks: 3,
    maxChannels: 0,
    maxBatchUrls: 0,
    cta: 'Get Developer',
    ctaHref: null,
    featured: false,
    description: 'For developers building apps and automations.',
    features: [
      '1,000 caption hours / month',
      '50 AI fallback hours / month',
      'No request-count quota',
      'REST API access',
      'No server-side transcript retention',
      'API key management and usage dashboard',
      'Webhooks up to 3',
      '100+ languages',
      'JSON, SRT, VTT, TXT formats',
    ],
    missing: ['No bulk dashboard', 'No channel sync'],
  },
  business: {
    name: 'Business',
    price: 79,
    priceLabel: '$79',
    period: '/ month',
    captionHoursPerMonth: 10000,
    aiFallbackHoursPerMonth: 500,
    allowanceLabel: '10,000 caption hours + 500 AI fallback hours',
    apiAccess: true,
    dashboard: true,
    webhooks: true,
    channelSync: true,
    batch: true,
    maxWebhooks: 20,
    maxChannels: 10,
    maxBatchUrls: 1000,
    cta: 'Get Business',
    ctaHref: null,
    featured: true,
    description: 'For agencies and teams that process content at scale.',
    features: [
      '10,000 caption hours / month',
      '500 AI fallback hours / month',
      'No request-count quota',
      'Everything in API plan',
      'Searchable transcript archive',
      'Durable batch queue for URLs and channels',
      'Channel auto-sync up to 10 channels',
      'Batch processing up to 1,000 URLs',
      'Webhooks up to 20',
      'Usage analytics',
    ],
    missing: [],
  },
  custom: {
    name: 'Custom',
    price: null,
    priceLabel: 'Custom',
    period: null,
    captionHoursPerMonth: null,
    aiFallbackHoursPerMonth: null,
    allowanceLabel: 'Custom hour allowance',
    apiAccess: true,
    dashboard: true,
    webhooks: true,
    channelSync: true,
    batch: true,
    maxWebhooks: -1,
    maxChannels: -1,
    maxBatchUrls: -1,
    cta: 'Contact us',
    ctaHref: 'mailto:easytran@proton.me',
    featured: false,
    description: 'For teams with high volume or special requirements.',
    features: [
      'Custom API volume',
      'SLA-backed reliability',
      'White-label options',
      'SSO and team management',
      'Priority support',
      'Custom integrations',
      'Dedicated onboarding',
    ],
    missing: [],
  },
} as const

export type PlanKey = keyof typeof PLANS
